#!/usr/bin/env python
"""
Usage: nj67-client.py <command> [<arguments>...]

<Commands>
  h, help      : Print this help message
  d, download  : Download files
  u, upload    : Upload files

<Arguments>
 -p, --path <path> : Specify the path in which to upload/download the file
"""

import argparse
import sys
import requests
import zipfile
import shutil
import tempfile
from pathlib import Path
from io import BytesIO

class Env:
    UPLOAD_PATH: Path = Path('ans_booklet')
    UPLOAD_URI: str = 'http://127.0.0.1:5000/upload'
    DOWNLOAD_URI: str = 'http://127.0.0.1:5000/download'
    DOWNLOAD_PATH: str | None = None

def init_parser():
    parser = argparse.ArgumentParser(description="NJ67 Client", add_help=False)
    subparsers = parser.add_subparsers(dest='command')
    subparsers.add_parser('help', aliases=['h', '-h', '--help'])
    download_parser = subparsers.add_parser('download', aliases=['d'])
    download_parser.add_argument('-p', '--path')
    upload_parser = subparsers.add_parser('upload', aliases=['u'])
    upload_parser.add_argument('-p', '--path')
    return parser

def download(env: Env):
    try:
        r = requests.get(env.DOWNLOAD_URI, params={})
    except requests.exceptions.ConnectionError:
        sys.exit("Error with connection, check that you are connected to the internet.")
    if r.status_code == 200:
        with zipfile.ZipFile(BytesIO(r.content), 'r') as zip_ref:
            zip_ref.extractall(path=env.DOWNLOAD_PATH)
    else:
        sys.exit(f"Error occured when downloading file (got status code {r.status_code})")

def upload(env: Env):
    try:
        temp_ans = tempfile.NamedTemporaryFile(prefix=env.UPLOAD_PATH.stem, suffix='.zip', delete=False)
        shutil.make_archive(temp_ans.name[:-4], 'zip', env.UPLOAD_PATH)
    except FileNotFoundError as e:
        sys.exit(f"No directory '{e.filename}' found")
    r = requests.post(env.UPLOAD_URI, files={'file': ('ans_booklet.zip', temp_ans, 'application/zip')})
    print(r.text)

env = Env()
try:
    args = init_parser().parse_args()
except SystemExit:
    sys.exit(__doc__)
if args.command in ('help', 'h', None):
    print(__doc__)
    sys.exit(0)
elif args.command in ('download', 'd'):
    env.DOWNLOAD_PATH = args.path or env.DOWNLOAD_PATH
    print(args.path)
    download(env)
elif args.command in ('upload', 'u'):
    env.UPLOAD_PATH = Path(args.path) if args.path else env.UPLOAD_PATH
    upload(env)