#!/usr/bin/env python
"""
Usage: nj67-client.py <command> [<arguments>...]

<Commands>
  h, help      : Print this help message
  d, download  : Download files
  u, upload    : Upload files

<Arguments>
 -p, --path <path> : Specify the path in which to upload/download the file
"""

import argparse
import sys
import requests
import zipfile
import shutil
import tempfile
import pickle
from pathlib import Path
from io import BytesIO


def get_config_dir(create=True, dir_name="nj67client"):
    "Get path of config directory, creating if not exists"
    def _from_parent(path: Path):
        c = path / dir_name
        if create:
            c.mkdir(exist_ok=True)
        return c
    # UNCOMMENT TO CAUSE HEADACHES ON WHERE CONFIG IS
    # if (a := Path('.') / '.vscode') and a.exists():
    #     return _from_parent(a)
    # match os.name:
    #     case 'posix':
    #         if (b := os.environ.get('XDG_CONFIG_DIR', '')) and Path(b).exists():
    #             return _from_parent(Path(b))
    #         elif ((a := os.environ.get('HOME', '')) or (a := Path.home())) and (b := (Path(a) / '.config')) and b.exists():
    #             return _from_parent(b)
    #         else:
    #             return _from_parent(Path())
    #     case 'nt':
    #         return _from_parent(Path.home() / 'AppData' / 'Roaming')
    #     case 'java':
    #         print("...bro wtf why java are u kidding me jython don't even support python 3 man wth")
    return _from_parent(Path())

class Env:
    UPLOAD_PATH: Path = Path('ans_booklet')
    UPLOAD_URI: str = 'http://127.0.0.1:5000/upload'
    DOWNLOAD_URI: str = 'http://127.0.0.1:5000/download'
    DOWNLOAD_PATH: str | None = None
    CONFIG_DIR = get_config_dir()
    COOKIE_FILE = CONFIG_DIR / "cookies-pickled"

class Cookie_env:
    def __init__(self):
        self.s = requests.Session()
        if env.COOKIE_FILE.exists():
            with open(env.COOKIE_FILE, 'rb') as f:
                self.s.cookies.update(pickle.load(f))
    def __enter__(self):
        return self.s
    def __exit__(self, type, value, traceback):
        with open(env.COOKIE_FILE, 'wb') as f:
            pickle.dump(self.s.cookies, f)
    
env = Env()
cookie_env = Cookie_env()

def init_parser():
    parser = argparse.ArgumentParser(description="NJ67 Client", add_help=False)
    subparsers = parser.add_subparsers(dest='command')
    subparsers.add_parser('help', aliases=['h', '-h', '--help'])
    download_parser = subparsers.add_parser('download', aliases=['d'])
    download_parser.add_argument('-p', '--path')
    upload_parser = subparsers.add_parser('upload', aliases=['u'])
    upload_parser.add_argument('-p', '--path')
    return parser

def download(env: Env):
    with cookie_env as sess:
        try:
            r = sess.get(env.DOWNLOAD_URI, params={})
        except requests.exceptions.ConnectionError:
            sys.exit("Error with connection, check that you are connected to the internet.")
    if r.status_code == 200:
        with zipfile.ZipFile(BytesIO(r.content), 'r') as zip_ref:
            zip_ref.extractall(path=env.DOWNLOAD_PATH)
    else:
        sys.exit(f"Error occured when downloading file (got status code {r.status_code})")

def upload(env: Env):
    try:
        temp_ans = tempfile.NamedTemporaryFile(prefix=env.UPLOAD_PATH.stem, suffix='.zip', delete=False)
        shutil.make_archive(temp_ans.name[:-4], 'zip', env.UPLOAD_PATH)
    except FileNotFoundError as e:
        sys.exit(f"No directory '{e.filename}' found")
    with cookie_env as sess:
        r = sess.post(env.UPLOAD_URI, files={'file': ('ans_booklet.zip', temp_ans, 'application/zip')})
    print(r.text)

try:
    args = init_parser().parse_args()
except SystemExit:
    sys.exit(__doc__)
if args.command in ('help', 'h', None):
    print(__doc__)
    sys.exit(0)
elif args.command in ('download', 'd'):
    env.DOWNLOAD_PATH = args.path or env.DOWNLOAD_PATH
    download(env)
elif args.command in ('upload', 'u'):
    env.UPLOAD_PATH = Path(args.path) if args.path else env.UPLOAD_PATH
    upload(env)