#!/usr/bin/env python
"""
Usage: nj67-client <command> [<arguments>...]

<Commands>
  h, help      : Print this help message
  d, download  : Download files
  u, upload    : Upload files

<Arguments>
 -p, --path <path> : Specify the path in which to upload/download the file
"""

import argparse
import os
import pickle
import requests
import shutil
import sys
import tempfile
import zipfile

from io import BytesIO
from pathlib import Path


def get_config_dir(create=True, dir_name="nj67client"):
    "Get path of config directory, creating if not exists"
    def _from_parent(path: Path):
        c = path / dir_name
        if create:
            c.mkdir(exist_ok=True)
        return c
    # GETTING CONFIG DIR FROM MORE HIDDEN SPOTS, NOT RECOMMENDED FOR SMALL-SCALE USE
    # if (a := Path('.') / '.vscode') and a.exists():
    #     return _from_parent(a)
    # match os.name:
    #     case 'posix':
    #         if (b := os.environ.get('XDG_CONFIG_DIR', '')) and Path(b).exists():
    #             return _from_parent(Path(b))
    #         elif ((a := os.environ.get('HOME', '')) or (a := Path.home())) and (b := (Path(a) / '.config')) and b.exists():
    #             return _from_parent(b)
    #     case 'nt':
    #         return _from_parent(Path.home() / 'AppData' / 'Roaming')
    #     case 'java':
    #         print("...bro wtf why java are u kidding me jython don't even support python 3 man wth")
    # return _from_parent(Path())
    return _from_parent(Path())

class Env:
    UPLOAD_PATH: Path = Path('ans_booklet')
    UPLOAD_URI: str = 'http://127.0.0.1:5000/upload'
    DOWNLOAD_URI: str = 'http://127.0.0.1:5000/download'
    DOWNLOAD_PATH: str | None = None
    CONFIG_DIR = get_config_dir()
    COOKIE_FILE = CONFIG_DIR / "cookies-pickled"

    def __init__(self, *, args: argparse.Namespace|None=None):
        if args is not None:
            if args.command in ('download', 'd'):
                self.DOWNLOAD_PATH = args.path or self.DOWNLOAD_PATH
            elif args.command in ('upload', 'u'):
                self.UPLOAD_PATH = Path(args.path) if args.path else self.UPLOAD_PATH

class Cookie_env:
    def __init__(self):
        self.s = requests.Session()
        if env.COOKIE_FILE.exists():
            with open(env.COOKIE_FILE, 'rb') as f:
                self.s.cookies.update(pickle.load(f))
    def __enter__(self):
        return self.s
    def __exit__(self, type, value, traceback):
        with open(env.COOKIE_FILE, 'wb') as f:
            pickle.dump(self.s.cookies, f)

def init_parser():
    parser = argparse.ArgumentParser(description="NJ67 Client", add_help=False)
    subparsers = parser.add_subparsers(dest='command')
    subparsers.add_parser('help', aliases=['h', '-h', '--help'])
    download_parser = subparsers.add_parser('download', aliases=['d'])
    download_parser.add_argument('-p', '--path')
    upload_parser = subparsers.add_parser('upload', aliases=['u'])
    upload_parser.add_argument('-p', '--path')
    return parser

try:
    args = init_parser().parse_args()
except SystemExit:
    sys.exit(__doc__)
env = Env(args=args)
cookie_env = Cookie_env()

def download():
    with cookie_env as sess:
        try:
            r = sess.get(env.DOWNLOAD_URI, params={})
        except requests.exceptions.ConnectionError:
            sys.exit("Error with connection, check that you are connected to the internet.")
    if r.status_code == 200:
        with zipfile.ZipFile(BytesIO(r.content), 'r') as zip_ref:
            zip_ref.extractall(path=env.DOWNLOAD_PATH)
    else:
        sys.exit(f"Error occured when downloading file (got status code {r.status_code})")

def upload():
    try:
        temp_ans = tempfile.NamedTemporaryFile(prefix=env.UPLOAD_PATH.stem, suffix='.zip', delete=False)
        shutil.make_archive(temp_ans.name[:-4], 'zip', env.UPLOAD_PATH)
    except FileNotFoundError as e:
        sys.exit(f"No directory '{e.filename}' found")
    with cookie_env as sess:
        r = sess.post(env.UPLOAD_URI, files={'file': ('ans_booklet.zip', temp_ans, 'application/zip')})
    print(r.text)

if args.command in ('help', 'h', None):
    print(__doc__)
    sys.exit(0)
elif args.command in ('download', 'd'):
    download()
elif args.command in ('upload', 'u'):
    upload()