#!/usr/bin/env python3
"""\
Webserver for users to be able to upload the files via the CLI or webpage.
"""
import os
import uuid

from datetime import datetime
from pathlib import Path
from zipfile import ZipFile

from werkzeug.security import safe_join
from flask import Flask, redirect, render_template, request, send_file, send_from_directory, session, url_for

app = Flask(__name__)
app.secret_key = os.environ.get("FLASK_SECRET_KEY", '')
if not app.secret_key:
    print("PLEASE set FLASK_SECRET_KEY environment variable so that user_id will not change with every server restart")
    app.secret_key = uuid.uuid4().hex
else:
    print("Flask secret key found in env variable FLASK_SECRET_KEY")

cwd = Path(app.root_path)
output_dir = cwd / 'output'
output_dir.mkdir(exist_ok=True)

@app.before_request
def create_if_not_exists_session():
    if 'user_id' not in session:
        session['user_id'] = str(uuid.uuid4())

@app.route('/')
def index():
    return send_from_directory(cwd / 'static', 'index.html')

@app.route('/favicon.ico')
def favicon():
    return send_from_directory(cwd / 'static', 'favicon.ico', mimetype='image/vnd.microsoft.icon')

@app.route('/upload', methods=['POST'])
def get_ans():
    out_dir = output_dir / session['user_id'] / datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
    out_dir.mkdir(parents=True, exist_ok=True)
    with ZipFile(request.files['file'].stream) as zip_ref:
        zip_ref.extractall(out_dir)
    contents = tuple(out_dir.iterdir())
    if len(contents) == 1 and contents[0].is_dir():
        try:
            for child in contents[0].iterdir():
                child.rename(out_dir / child.name)
            contents[0].rmdir()
        except OSError: 
            return "Error: invalid zip file", 500
    return 'ok', 200

@app.route('/download', methods=['GET'])
def papers_please():
    if request.args:
        pass #TODO
    return redirect('/static/papers.zip')

@app.route('/view/', methods=['GET'])
def view_uploads():
    uploads = output_dir / session['user_id']
    if not uploads.exists():
        return "File not found", 404
    if request.args.get('list', False, bool):
        return [a.name for a in uploads.iterdir()], 200
    return render_template('view_files.html.jinja',
        title="Uploaded files by timestamp",
        files=list(map(lambda a: a.name, uploads.iterdir())))
@app.route('/view')
def view():
    if request.args.get('list', False, bool):
        uploads = output_dir / session['user_id']
        return [a.name for a in uploads.iterdir()], 200
    return redirect('/view/')

@app.route('/view/<path:path>/', methods=['GET'])
def view_files(**kwargs):
    path = safe_join(output_dir / session['user_id'], kwargs['path'])
    if path is None or not ( path := Path(path) ).exists():
        return "File not found", 404
    if path.is_dir():
        return render_template(
            'view_files.html.jinja',
            title="Files in submission",
            files=list(map(lambda a: a.name, path.iterdir())))
    else:
        return send_file(path) # since 'path' already uses werkzeug.security.safe_join()

# This route declaration must be below the one for '/view/<path:path>/' 
# or else it will lead to recurion of '/' constantly being appended to url string
@app.route('/view/<path:path>')
def redirect_view_files(**kwargs):
    return redirect(url_for('view_files', **kwargs))

if __name__ == '__main__':
    app.run(host="0.0.0.0", debug=True)