#!/usr/bin/env python
"""
Collection of functions to parse ipynb
"""
import json
import re
import sys

from pathlib import Path

def get_subtask_from_cell(cell: dict):
    "Attempt to get the subtask number for the cell, returns 0 if not found"
    try:
        return cell['metadata']['nj67']["subtask"]
    except KeyError:
        pass
    try:
        tags = cell['metadata']['tags']
        for tag in tags:
            if tag[:4].lower() == 'task':
                try:
                    return int(tag.split('.')[-1])
                except ValueError:
                    continue
    except KeyError:
        pass
    # source can either be single string or list of strings
    try:
        head = cell['source'].split('\n')[0]
    except AttributeError:
        head = cell['source'][0]
    if (task_string := re.match(r"task\s*\d+\.(\d+)", head, re.IGNORECASE)) is not None:
        return int(task_string.group(1))
    return 0

def proc_file(file):
    "Return list of cells ordered by subtask, will raise Exceptions if missing too much metadata"
    with open(file) as f:
        nb = json.load(f)
    try:
        no_subtask = nb['metadata']['nj67']['no_subtask']
        task_no = nb['metadata']['nj67']['task_no']
    except KeyError:
        raise NotImplementedError(f"No metadata found in file: {file}")
    all_cell_tuples = [(get_subtask_from_cell(cell), cell) 
                    for cell in nb['cells'] if cell['cell_type'] == "code"]
    i = 1 # expected subtask of cell, subtassks are 1-indexed
    ordered_cells = []
    for cell_index, cell_tup in enumerate(all_cell_tuples):
        if cell_tup[0] == i:
            ordered_cells.append(cell_tup[1])
            i += 1
            continue
        j = 1
        try:
            while True:
                if all_cell_tuples[cell_index + j][0] == i:
                    print(f"Found extra code cell{'s' if j > 1 else ''} after Task {task_no}.{i-1}, ignoring...", file=sys.stderr)
                    break
                elif all_cell_tuples[cell_index + j][0] == i + j:
                    ordered_cells.append(cell_tup[1])
                    print(f"Found code cell with missing metadata, ignoring...", file=sys.stderr)
                    break
                elif all_cell_tuples[cell_index + j][0] in range(i, i+j):
                    raise NotImplementedError(f"Found code cell(s) with missing metadata and ambigous ordering")
                j += 1
            continue
        except IndexError: #End of cells
            print(i, j)
            if i + j - 1 == no_subtask:
                ordered_cells.extend(map(lambda tup: tup[1], all_cell_tuples[i-1:]))
                print("Found cell(s) with missing metadata until eof, ignoring...")
                break
            raise NotImplementedError(f"Found code cell(s) with missing metadata and ambigous ordering")
    return ordered_cells

def add_cell_metadata(file):
    """
    Add metadata of subtask number to code cells and task number to notebook itself
    
    Will fail if the name of the ipynb does not follow the format task_n\

    Filename will take precedence over existing metadata
    """
    fp = Path(file)
    with fp.open() as f:
        nb = json.load(f)
    if (task_no := re.match(r"TASK_?(\d+)", fp.name, re.IGNORECASE)):
        nb['metadata']['nj67']['task_no'] = int(task_no.group(1))
    try:
        no_subtask = nb['metadata']['nj67']['no_subtask']
    except KeyError:
        raise NotImplementedError("Unable to find task number from file name or metadata")
    i = 1
    for cell in nb['cells']: 
        if cell['cell_type'] != "code":
            continue
        if 'metadata' not in cell:
            cell['metadata'] = {}
        cell['metadata']['nj67'] = {"subtask": i}
        cell['metadata']['tags'] = [f"task {no_subtask}.{i}"] + cell['metadata'].get('tags', [])
        cell['source'] = [f"# Task {no_subtask}.{i}", "# YOUR CODE HERE"]
        i += 1
    
    with fp.with_stem(fp.stem + '_processed').open('w') as f:
        json.dump(nb, f, indent=2)

# add_cell_metadata("task_67.ipynb")
# print(*proc_file("task_67_processed.ipynb"),sep='\n\n')