#!/usr/bin/env python
"""
Script to be run on the server.
"""

from datetime import datetime
from pathlib import Path
from zipfile import ZipFile

from flask import Flask, redirect, request, send_from_directory

app = Flask(__name__)

cwd = Path(__file__).parent
(cwd / 'output').mkdir(exist_ok=True)

@app.route('/')
def index():
    return send_from_directory(Path(__file__).parent / 'static', 'index.html')

@app.route('/upload', methods=['POST'])
def get_ans():
    # TODO: Add UUID? to each client to differentiate different people
    out_dir = cwd / f'output/{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}_{request.remote_addr}'
    with ZipFile(request.files['file'].stream) as zip_ref:
        zip_ref.extractall(out_dir)
    contents = tuple(out_dir.iterdir())
    if len(contents) == 1 and contents[0].is_dir():
        try:
            for child in contents[0].iterdir():
                child.rename(out_dir / child.name)
            contents[0].rmdir()
        except OSError: 
            return "Error: invalid zip file", 500
    return 'ok', 200

@app.route('/download', methods=['GET'])
def papers_please():
    if request.args:
        pass #TODO
    return redirect('/static/papers.zip')

if __name__ == '__main__':
    app.run(host="0.0.0.0", debug=True)